### ISSUE TITLE
App\Response\HTML doesn't seem to be recognized as html

### ISSUE THREAD

**Issue by emerika** [bearframework/bearframework#4]
This probably a pilot error, but the code below doesn't result in a interpreted output-just text.
I added the setContentType just because it wasn't working -- not because I thought I needed it.

$app->routes->add('/info/', function() {
    $html = phpinfo();
    $page = new App\Response\HTML($html);
    $page->setContentType('text/html');
    return $page;
});

Request URL:https://www.emerika.com/info/
Request Method:GET
Status Code:503 Service Unavailable
Remote Address:45.79.96.87:443

**Comment by ivopetkov** [comment]
The PHP function `phpinfo` outputs HTML and does not return anything valuable. In your case `$html = true` which is invalid argument for `App\Response\HTML` and an error is triggered.

You can do this:

```
ob_start();
phpinfo();
$html = ob_get_clean();
return new App\Response\HTML($html);
```

Maybe we should think of an easy way to convert an output to a response object.
