### ISSUE TITLE
PHP 8.2 compliant ?

### ISSUE THREAD

**Issue by waghanza** [bearframework/bearframework#6]
Hi @ivopetkov,

I can see that `bearframework` is not ready for 8.2
https://github.com/the-benchmarker/web-frameworks/actions/runs/6440193516/job/17488760283?pr=6782#step:7:1121

Is there a plan to support this version ?

Regards,

**Comment by ivopetkov** [comment]
Just released v1.13 that supports PHP 8.2.

**Comment by waghanza** [comment]
@ivopetkov seems not to be the case
```
0.687     - bearframework/bearframework v1.13.0 requires php 7.1.*|7.2.*|7.3.*|7.4.*|8.0.*|8.1.* -> your php version (8.2.5) does not satisfy that requirement.
```

https://packagist.org/packages/bearframework/bearframework#v1.13.0

**Comment by ivopetkov** [comment]
Fixed :)
Thanks.
